package dev.sdp.core.algebra

/** Renders dataset shapes as Scala 3 named-tuple type aliases — the
  * type-provider half of the Codegen-Oracle architecture (F14b).
  *
  * Output is deterministic (datasets sorted, columns in shape order) and
  * intended to be written to a *checked-in* source file: the catalog (or the
  * pipeline's own inference) is the source of truth, and schema changes show
  * up as reviewable diffs — the property the typed-columns research singled
  * out as the reason codegen beats both inference-only and hand-maintained
  * declarations.
  */
object SchemaCodegen:

  /** One generated alias: dataset name → its known columns. */
  final case class Entry(dataset: String, columns: List[(String, ColType)], origin: String)

  def render(packageName: String, entries: List[Entry]): String =
    val header =
      s"""// Generated by sbt-spark-pipelines (sdpImportSchemas). Check in; regenerate to refresh.
         |// Datasets with unknowable shapes (SQL bodies, undeclared sources) are omitted.
         |package $packageName
         |
         |""".stripMargin

    val aliases = entries
      .sortBy(_.dataset)
      .map { entry =>
        val cols = entry.columns
          .map((name, tpe) => s"${ident(name)}: ${scalaType(tpe)}")
          .mkString(", ")
        s"""/** ${entry.dataset} — ${entry.origin} */
           |type ${typeName(entry.dataset)} = ($cols)
           |""".stripMargin
      }
      .mkString("\n")

    header + aliases

  /** `raw_events` → `RawEvents`; anything non-identifier-ish is sanitized. */
  def typeName(dataset: String): String =
    dataset
      .split("[^A-Za-z0-9]+")
      .filter(_.nonEmpty)
      .map(part => part.head.toUpper.toString + part.tail)
      .mkString match
      case s if s.isEmpty || !s.head.isLetter => s"Dataset$s"
      case s                                  => s

  private def ident(name: String): String =
    val simple = name.nonEmpty && name.head.isLetter && name.forall(c => c.isLetterOrDigit || c == '_')
    if simple then name else s"`$name`"

  private def scalaType(t: ColType): String = t match
    case ColType.Bool      => "Boolean"
    case ColType.I32       => "Int"
    case ColType.I64       => "Long"
    case ColType.F64       => "Double"
    case ColType.Str       => "String"
    case ColType.Timestamp => "java.sql.Timestamp"
    case ColType.Date      => "java.sql.Date"
    // label-only checking: cols[S] types every field ExArg anyway, so an
    // unknown column type costs nothing — the LABEL is the safety.
    case ColType.Unknown   => "Any"
